### ISSUE TITLE
CreateRevisionsTable Ambiguous

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/Demo#55] opened 2018-01-13 10:19 UTC
# Bug report

Haven't looked into this currently, but just putting this out there so we can look at it and avoid a bad first user experience.

### What I did:

```
composer install
```

OR

```
composer update
```

### What I expected to happen:

install without errors

### What happened:

got error

```
Warning: Ambiguous class resolution, "CreateRevisionsTable" was found in both "$baseDir . '/database/migrations/2013_04_09_062329_create_revisions_table.php" and "/Users/abby/Sites/backpack-demo/vendor/venturecraft/revisionable/src/migrations/2013_04_09_062329_create_revisions_table.php", the first will be used.
```

### Backpack, Laravel, PHP, DB version:
- Backpack/Base: 0.8.6
- Backpack/Crud: 3.3.5
- Laravel/framework: 5.5.x-dev
- PHP: 7.1.7

**Comment by lloy0076** [comment] 2018-01-13 13:12
It seems there really are two.

**Comment by lloy0076** [comment] 2018-01-13 13:14
* https://github.com/VentureCraft/revisionable/blob/master/src/migrations/2013_04_09_062329_create_revisions_table.php
* https://github.com/Laravel-Backpack/Demo/blob/master/database/migrations/2013_04_09_062329_create_revisions_table.php

The easiest way would be to just drop ours; or at least rename it.

**Comment by AbbyJanke** [comment] 2018-01-13 13:14
Suspected as similar, but it is not a `breaking` change, but in my experience even any minor issue is kind of a turn-off for users.

**Comment by lloy0076** [comment] 2018-01-13 15:03
And I can't reproduce it...

**Comment by tabacitu** [comment] 2018-02-12 11:36
Fixed in https://github.com/Laravel-Backpack/Demo/pull/56

Thank you!

**Closed by tabacitu** 2018-02-12 11:36 UTC
Labels: bug
