### ISSUE TITLE
DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by averuga** [Laravel-Backpack/Demo#49] opened 2017-11-16 10:53 UTC
# Bug report
Settings Error detected: "DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

LangFileManager - the same proplem

Screens -https://yadi.sk/d/6nFNfLC43PkWEg

### What I did:
Install Demo https://laravel-backpack.readme.io/docs/demo
Install LangFileManager https://github.com/Laravel-Backpack/langfilemanager
 
 ### Backpack, Laravel, PHP, DB version:
Last ver.  + Laravel Homestead fresh install (MariaDB) 
 PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 (cli)
mysql  Ver 15.1 Distrib 10.1.28-MariaDB, for debian-linux-gnu (x86_64)

**Comment by sh4dw** [comment] 2017-11-16 22:50
Same. When you inspect the Datatables request it seems like:
**Langfilemanager (/admin/language)**
URL: `/admin/language/search?`
**And Settings /admin/setting**
URL: `/admin/setting/search?`

Are both causing:
`Backpack \ CRUD \ Exception \ AccessDeniedException
Unauthorized access - you do not have the necessary permissions to see this page.`
From:
`/vendor/backpack/crud/src/PanelTraits/Access.php90`

**Comment by jobith93** [comment] 2017-11-17 10:07
What is the Solution to this issue ? Please Help

**Comment by mdiannna** [comment] 2017-11-27 15:35
The problem is  `Route::resource('language', 'LanguageCrudController'); ` in `vendor/backpack/langfilemanager/src/app/Http/routes.php`
that should be` CRUD::resource('language', 'LanguageCrudController');`

A solution would be to add `CRUD::resource('language', '\Backpack\LangFileManager\app\Http\Controllers\LanguageCrudController');`
in routes/admin.php.

**Comment by tabacitu** [comment] 2017-11-29 10:41
Hi guys, thanks for the bug report. The Backpack\Settings package has had a fix for this for a while now, it just wasn't used in the demo. A simple ```composer update``` should fix it for you guys. I've update Backpack\Demo accordingly, just now.

Cheers!

**Closed by tabacitu** 2017-11-29 10:41 UTC

**Comment by haitong506** [comment] 2018-07-02 16:57
you can see it
http://123link.pw/diAAQi

**Comment by haitong506** [comment] 2018-09-27 02:18
DataTables warning: table id=example - Ajax error. For more information about this error, please see http://datatables.net/tn/7 You can see it in this link http://123link.pw/diAAQi
