### ISSUE TITLE
Laravel error when changing anything

### ISSUE THREAD

**Issue by Badestrand** [Laravel-Backpack/Demo#27] opened 2017-04-05 14:42 UTC
Hi

I installed the demo according to the docs at https://laravel-backpack.readme.io/docs/demo.

I run the web server from the folder with `php artisan serve`.

Whenever I try to change something, e.g. add a menu item I get the error:

BadMethodCallException in Builder.php line 2450:
Call to undefined method Illuminate\Database\Query\Builder::getCastedAttributes()

Full stack:
```
in Builder.php line 2450
at Builder->__call('getCastedAttributes', array()) in Builder.php line 1473
at Builder->__call('getCastedAttributes', array()) in Model.php line 3561
at Model->__call('getCastedAttributes', array()) in Fields.php line 200
at CrudPanel->decodeJsonCastedAttributes(array('_token' => 'lVOhmMKV6zosPe4F3Ze4ubB3vgansU6nlTC3bUxw', 'name' => 'zxczxc', 'email' => 'zxczxc@asd.com', 'password' => 'asd', 'password_confirmation' => 'asd', 'save_action' => 'save_and_back'), 'create') in Create.php line 22
at CrudPanel->create(array('_token' => 'lVOhmMKV6zosPe4F3Ze4ubB3vgansU6nlTC3bUxw', 'name' => 'zxczxc', 'email' => 'zxczxc@asd.com', 'password' => 'asd', 'password_confirmation' => 'asd', 'save_action' => 'save_and_back')) in UserCrudController.php line 117
at UserCrudController->store(object(UserStoreCrudRequest))
at call_user_func_array(array(object(UserCrudController), 'store'), array(object(UserStoreCrudRequest))) in Controller.php line 55
at Controller->callAction('store', array(object(UserStoreCrudRequest))) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(UserCrudController), 'store') in Route.php line 189
at Route->runController() in Route.php line 144
at Route->run(object(Request)) in Router.php line 653
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CrudController.php line 41
at CrudController->Backpack\CRUD\app\Http\Controllers\{closure}(object(Request), object(Closure)) in Pipeline.php line 120
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Admin.php line 29
at Admin->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Router.php line 655
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 629
at Router->dispatchToRoute(object(Request)) in Router.php line 607
at Router->dispatch(object(Request)) in Kernel.php line 268
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 150
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
at Kernel->handle(object(Request)) in index.php line 52
at require_once('/Users/xxx/Desktop/admin-test/backpack-demo/public/index.php') in server.php line 19
```

**Comment by tabacitu** [comment] 2017-04-05 15:13
Hi @Badestrand ,

Thanks a lot for reporting this. I've made a fresh install and can confirm the issue is present.

I'm on it!

**Comment by tabacitu** [comment] 2017-04-05 15:19
Got it!

**Please run a ```composer update```, that will fix it.** As an alternative - reinstall the demo.

The issue has long been fixed in Backpack\CRUD, but the Demo was not up to date. I've updated it now, so other users that test it won't have this issue. 

Again, thanks a lot for reporting this.
Cheers!

**Closed by tabacitu** 2017-04-05 15:19 UTC

**Comment by Badestrand** [comment] 2017-04-05 15:29
Thank you for that quick fix!
